using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DataBase;
using DataBase.Data;
#pragma warning disable CS8632 // The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.

namespace ASPwebApp.Controllers
{
    [Route("api/Item")]
    [ApiController]
    public class ItemController : ControllerBase
    {
        private readonly MyDbContext _context;
        private readonly UnitOfWork uow;
        public ItemController(MyDbContext context)
        {
            _context = context;
            uow = new UnitOfWork(_context);
        }
        /// <summary>
        /// Autogenerated get list of items (Associated with user)
        /// </summary>
        /// <returns></returns>
        // GET: api/Item2
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Item>>> GetItem()
        {
            return await _context.Item.ToListAsync();
        }
        /// <summary>
        /// Get 1 item by DB item Id
        /// </summary>
        /// <param name="id">item id as listed in DB</param>
        /// <returns></returns>
        // GET: Item/Details/5
        [HttpGet("byId/{id}")]
        public async Task<ActionResult<SimpleItem>> FromId(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = uow.Items.Get((int)id);
            //= await _context.Item
            //.FirstOrDefaultAsync(m => m.ItemId == id);
            if (item == null)
            {
                return NotFound();
            }
            var simpleItem = new SimpleItem(item);
            return simpleItem;
        }
        /// <summary>
        /// Get 1 item by barcode
        /// </summary>
        /// <param name="ean"></param>
        /// <returns></returns>
        [HttpGet("byEan/{ean}")]
#pragma warning disable 8632
        public async Task<ActionResult<SimpleItem>> FromEan(string? ean)
#pragma warning restore 8632
        {
            if (ean == null)
            {
                return NotFound();
            }

            var item = await uow.Items.GetItemWithEan(ean);
            if (item == null)
            {
                return NotFound();
            }
            var simpleItem = new SimpleItem(item);
            return simpleItem;
        }
        /// <summary>
        /// Get 1 item by name
        /// </summary>
        /// <param name="name">this version is used like /api/item/byname/smør</param>
        /// /// <param name="superName">this version is used like /api/item/byname?name=smør</param>
        /// <returns></returns>
        [HttpGet("byName/{name}")]
        [HttpGet("byName")]
        public async Task<ActionResult<SimpleItem>> FromName(string? superName,[FromQuery]string? name)
        {
            if (name == null && superName == null) return NotFound("Vi mangler et navn");
            if (name == null )
            {
                name = superName;
            }
            var item = uow.Items.Find(i =>
                           i.Name.ToLower() == (name.ToLower())).FirstOrDefault()
                      ?? uow.Items.Find(i => //findes ikke et eksakt match, søges bredere:
                          i.Name.ToLower().Contains(name.ToLower())).FirstOrDefault();
            
            if (item == null)
            {
                return NotFound();
            }
            var simpleItem = new SimpleItem(item);
            return simpleItem;
        }



        /// <summary>
        /// Edit details about item
        /// </summary>
        /// <param name="newItem">item to be updated</param>
        /// <returns></returns>
        // GET: Item/Edit/5
        [HttpPut]
        public async Task<ActionResult<Item>> Edit([FromBody] Item newItem)
        {
            if (newItem == null)
            {
                return NotFound("Request var tom");
            }

            if (newItem.ItemId == null)
            {
                return NotFound("Mangler id");
            }



            _context.Entry(newItem).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ItemExists(newItem.ItemId))
                {
                    return NotFound("Item id did not match any item");
                }
                else
                {
                    throw;
                }
            }

            return Accepted();
        }

        private bool ItemExists(int id)
        {
            return _context.Item.Any(e => e.ItemId == id);
        }
    }
}
