// <auto-generated />

using DataBase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataBase.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210319134718_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InventoryItem", b =>
                {
                    b.Property<int>("InventoryCollectionInventoryId")
                        .HasColumnType("int");

                    b.Property<int>("ItemCollectionItemId")
                        .HasColumnType("int");

                    b.HasKey("InventoryCollectionInventoryId", "ItemCollectionItemId");

                    b.HasIndex("ItemCollectionItemId");

                    b.ToTable("InventoryItem");
                });

            modelBuilder.Entity("PantryBEtest.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PpUserEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InventoryId");

                    b.HasIndex("PpUserEmail");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("PantryBEtest.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("PantryBEtest.PpUser", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("PpUser");
                });

            modelBuilder.Entity("InventoryItem", b =>
                {
                    b.HasOne("PantryBEtest.Inventory", null)
                        .WithMany()
                        .HasForeignKey("InventoryCollectionInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PantryBEtest.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemCollectionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PantryBEtest.Inventory", b =>
                {
                    b.HasOne("PantryBEtest.PpUser", null)
                        .WithMany("Inventories")
                        .HasForeignKey("PpUserEmail");
                });

            modelBuilder.Entity("PantryBEtest.PpUser", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
